apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "city-population-api.fullname" . }}-config
  labels:
    {{- include "city-population-api.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_HOST: {{ .Values.elasticsearch.host | quote }}
  ELASTICSEARCH_PORT: {{ .Values.elasticsearch.port | quote }}
  ELASTICSEARCH_SCHEME: {{ .Values.elasticsearch.scheme | quote }}
