# Default values for city-population-api.

replicaCount: 1

image:
  repository: city-population-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 20
  periodSeconds: 5
  failureThreshold: 6

elasticsearch:
  enabled: true
  host: ""
  port: 9200
  scheme: http
  image:
    repository: elasticsearch
    tag: "8.12.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 1Gi
